### ISSUE TITLE
Bug Report - SSH MCP Server

### ISSUE THREAD

**Issue by elciospy** [tufantunc/ssh-mcp#10]
## Problem Information

**Package:** ssh-mcp  
**Version:** 1.0.8 (latest)  
**Repository:** https://github.com/tufantunc/ssh-mcp  
**Report Date:** January 2025

## Error Description

The SSH MCP Server is throwing the error `keyValidator._parse is not a function` when trying to execute commands via MCP, even with correct configuration and working SSH connectivity.

## Environment

- **Operating System:** Windows 10 (10.0.19045)
- **Node.js:** v20.15.0
- **NPM:** 10.7.0
- **MCP Client:** Cursor IDE v1.7.12

## Configuration Used

```json
{
  "mcpServers": {
    "ssh-mcp": {
      "command": "npx",
      "args": [
        "ssh-mcp",
        "-y",
        "--",
        "--host=HOST",
        "--port=2222",
        "--user=USER ",
        "--password=$$$$$",
        "--timeout=30000"
      ]
    }
  }
}
```

### ✅ Expected

- MCP SSH should connect and execute remote commands
- `exec` tool should be available for command execution

### ❌ Actual

- Error: `MCP error -32603: keyValidator._parse is not a function`
- `exec` tool is not available
- MCP SSH cannot process commands

### 1. Direct SSH Connectivity

```bash
ssh -o ConnectTimeout=10 -o BatchMode=yes mccoa826@69.49.241.35 -p 2222 "echo 'SSH connection test successful'"
```

**Result:** ✅ **SUCCESS** - SSH connectivity working perfectly

### 2. SSH Key Test

```bash
ssh -i "C:\Users\elcio\.ssh\id_rsa" mccoa826@69.49.241.35 -p 2222 "echo 'SSH connection test successful'"
```

**Result:** ✅ **SUCCESS** - SSH key working

### 3. SSH Key Format

```bash
Get-Content "C:\Users\elcio\.ssh\id_rsa" -Head 5
```

**Result:** Key in OpenSSH format (`-----BEGIN OPENSSH PRIVATE KEY-----`)

### 4. SSH-MCP Package Test

```bash
npx ssh-mcp --version
```

**Result:** ❌ **ERROR** - Same validation error

### 5. Direct Arguments Test

```bash
npx ssh-mcp --host=69.49.241.35 --port=2222 --user=USER --password=$$$$$ --timeout=30000
```

**Result:** ✅ **SUCCESS** - Server starts correctly ("SSH MCP Server running on stdio")

## Problem Analysis

The error `keyValidator._parse is not a function` suggests:

1. **Internal validation issue:** The package has a bug in the key validation function
2. **Dependency incompatibility:** Possible conflict with dependency versions
3. **Key format:** May have incompatibility with OpenSSH vs traditional RSA keys

## Additional Evidence

- The SSH-MCP server **starts correctly** when run directly
- The problem occurs **only via MCP** (Model Context Protocol)
- SSH connectivity **works perfectly** via terminal
- Configuration is **100% compliant** with official documentation

## Error Logs

```
MCP error -32603: keyValidator._parse is not a function
```

## Solutions Attempted

1. ✅ Fixed configuration (separator `--` before arguments)
2. ✅ Tested with password authentication (instead of key)
3. ✅ Verified SSH connectivity
4. ✅ Tested with latest version (1.0.8)
5. ✅ Verified SSH key format

## Impact

- **Affected functionality:** Remote command execution via MCP
- **Current workaround:** Using direct SSH commands via terminal
- **Severity:** Medium (alternative functionality available)

## Request

We would like:

1. **Investigation** of the `keyValidator._parse is not a function` error
2. **Fix** for the internal validation bug
3. **Compatibility** with OpenSSH keys
4. **Testing** with Node.js v20.15.0 on Windows

## Contact Information

- **Environment:** Local development
- **Priority:** Medium
- **Available for testing:** Yes

---

**Note:** This report was automatically generated based on performed tests. All information has been verified and is accurate.

**Comment by tufantunc** [comment]
Hi @elciospy, thank you for reporting that bug. I'm working on it.

**Comment by tufantunc** [comment]
I fixed the issue in the new version.

The problem occurred after upgrading Zod from v3 to v4. The Zod v4 package was incompatible with the codebase, so I downgraded it back to v3.

This was a very basic issue that I should have caught before releasing the new version of the package. Because of this, I’ve added some tests to run on a basic server locally and in GitHub Actions. From now on, whenever I update packages or add new features, I will make sure to test them properly.
